Issue-111 - If level is omitted, then the log level should be "Verbose"
microsoft/windows-container-tools pull request #112
Opened 2023-01-07 00:18 UTC by kimpanatopimizely

"level (Optional): This string field specifies the verboseness of the events collected. These include Critical, Error, Warning, and Information. If the level is not specified, the tool displays all events in the named channel, spanning various levels."

2023-01-07 00:24 UTC, kimpanatopimizely commented
@microsoft-github-policy-service agree

2023-01-07 07:29 UTC, profnandaa commented
@kimpanatopimizely -- thanks for your contribution! 🎉 Will review.

2023-01-07 07:33 UTC, profnandaa commented
/link issue #111

2023-01-11 07:53 UTC, profnandaa reviewed
Other that, everything else looks good to me. Thanks for spotting the issue and doing a fix!

2023-01-11 07:53 UTC, profnandaa commented on LogMonitor/src/LogMonitor/ConfigFileParser.cpp
> +    bool levelKeyExists {};
nit: I'd prefer just `false` instead of `{}`, this is C++20 right?

2023-01-11 09:16 UTC, profnandaa commented
See updated conversation here - https://github.com/microsoft/windows-container-tools/issues/111#issuecomment-1378431533

2023-01-11 12:45 UTC, kimpanatopimizely commented
Code change reverted and documentation for Event Log updated.
Should it also be updated for ETW Monitoring?

2023-01-13 15:57 UTC, CharityKathure requested changes
LGTM, however, please confirm that If the event log level is not specified, the level should be by default set to `Error`, and not `Warning`

2023-01-15 10:37 UTC, kimpanatopimizely commented
Changed from 'Warning' to 'Error'

2023-01-16 07:24 UTC, CharityKathure approved these changes

2023-01-17 11:17 UTC, profnandaa approved these changes

2023-01-17 11:19 UTC, merged